### ISSUE TITLE
Error for the tasks start or dist

### ISSUE THREAD

**Issue by outsideMyBox** [typesafehub/activator-hello-play-2_3-scala#4]
Hi,

The task 'run' works well but I get an error when I launch 'activator start' or 'activator dist':

```
[hello-play-2_3-scala] $ start
[info] Wrote /home/franck/projects/misc/activator-hello-play-2_3-scala/target/scala-2.10/hello-play-2_3-scala_2.10-1.0-SNAPSHOT.pom
[info] Error: Error: /home/franck/projects/misc/activator-hello-play-2_3-scala/target/web/rjs/appdir/./main.js does not exist.
[info]     at /home/franck/projects/misc/activator-hello-play-2_3-scala/project/target/node-    modules/webjars/requirejs/bin/r.js:26721:27
[trace] Stack trace suppressed: run last *:webPipeline for the full output.
[error] (*:webPipeline) com.typesafe.sbt.jse.SbtJsTask$JsTaskFailure: 

Cannot start with errors.
[hello-play-2_3-scala] $ last *:webPipeline
com.typesafe.sbt.jse.SbtJsTask$JsTaskFailure: 
        at     com.typesafe.sbt.jse.SbtJsTask$$anonfun$com$typesafe$sbt$jse$SbtJsTask$$executeJsOnEngine$    1.apply(SbtJsTask.scala:204)
        at     com.typesafe.sbt.jse.SbtJsTask$$anonfun$com$typesafe$sbt$jse$SbtJsTask$$executeJsOnEngine$    1.apply(SbtJsTask.scala:176)
        at scala.util.Success$$anonfun$map$1.apply(Try.scala:206)
        at scala.util.Try$.apply(Try.scala:161)
        at scala.util.Success.map(Try.scala:206)
        at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
        at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
        at     scala.concurrent.impl.ExecutionContextImpl$$anon$3.exec(ExecutionContextImpl.scala:107)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[error] (*:webPipeline) com.typesafe.sbt.jse.SbtJsTask$JsTaskFailure: 
```

(I am using node for sbt-rjs, but I get a similar error with Trireme)

**Comment by ghost** [comment]
hi, did you find a solution for the above problem? it looks like exactly the same message i've got today... :(

**Comment by muellenborn** [comment]
sry, old account... but it's still the question? did you get a solution for that issue?

**Comment by outsideMyBox** [comment]
Hi,
I didn't. I don't remember what I did exactly then, I think I used another seed from 'activator ui'.
For Play 2.4.0 you can also try the seed [play-scala-preview](https://github.com/ajozwik/play-scala-preview)
